import re

SEPARATORS = re.escape(',.:;!? ')

##
## Mandatory group definitions
##

# Privileged groups
OWNER_GROUP = 'owner'
ADMIN_GROUP = 'admin'


##
## Command attributes
##

COMMAND_ARGS = '__COMMAND_ARGS__'
COMMAND_DESC = '__COMMAND_DESC__'
COMMAND_TRIGGERS = '__COMMAND_TRIGGERS__'
COMMAND_TIMEOUT = '__COMMAND_TIMEOUT__'
COMMAND_DMONLY = '__COMMAND_DMONLY__'
COMMAND_USER_GROUPS = '__COMMAND_USER_GROUPS__'
COMMAND_CHANNEL_GROUPS = '__COMMAND_CHANNEL_GROUPS__'
